Add helper script to run all check (for example before pushing)
serlo/serlo.org-database-layer pull request #114
Opened 2021-06-24 15:32 UTC by kulla

2021-06-24 15:46 UTC, elbotho commented
> Hopefully I will open less PRs with errors in the future 😄 🙈 

Just as a side note: PRs with errors might feel bad, but are not a real problem imo.
That's why we have the checks running here.
Some companies even encourage devs not to slow down their machines by running checks and builds locally :)

Still like the helpers 👍

2021-06-25 13:30 UTC, inyono requested changes

2021-06-25 13:30 UTC, inyono commented on scripts/run_all_checks.sh
> +	sleep 20
This should probably use something like https://github.com/serlo/serlo.org-database-layer/blob/main/.github/wait-for-server.sh instead.

2021-06-26 12:51 UTC, kulla commented
@inyono Review suggestions implemented. Ready to be merged

2021-07-02 11:47 UTC, inyono approved these changes
LGTM. I added `prettier-plugin-sh` so that the bash scripts get also formatted. The only thing I noticed is that this still requires `yarn start` beforehand. We could possibly add that to the script, too (since `yarn start` won't do much if the server has already been started).

2021-07-02 14:58 UTC, merged