Add UserSetEmailMutation
serlo/serlo.org-database-layer pull request #166
Opened 2022-01-25 10:22 UTC by hugotiburtino

2022-01-25 11:06 UTC, hugotiburtino commented
At the test it would be good to check if the email was indeed updated, but it would demand a lot of work now. Let me put it in my TODO list and move on.

2022-01-25 12:11 UTC, kulla requested changes

2022-01-25 12:11 UTC, kulla commented on server/tests/user.rs
> +        assert_ok(mutation_response, json!({ "success": true })).await;
Please add a check that the the mail was changed properly (via sqlx query)

2022-01-26 16:43 UTC, kulla approved these changes

2022-01-26 16:44 UTC, merged