Add TaxonomyCreateEntityLinkMutation
serlo/serlo.org-database-layer pull request #221
Opened 2022-04-29 12:47 UTC by hugotiburtino

See #210

2022-04-29 23:49 UTC, hugotiburtino commented
- [ ] Should not run on CoursePage, GroupedExercise and Solution(?)

2022-05-05 07:59 UTC, kulla requested changes

2022-05-05 07:59 UTC, kulla commented on server/src/uuid/model/entity/mod.rs
> +        }) = Self::fetch_via_transaction(id, executor).await
This would result in `Ok(())` for all other `sqlx::Error` -> Try 

```rs
Self::fetch_via_transaction(...).await.map_err(....)
```

2022-05-05 07:59 UTC, kulla commented on server/src/uuid/model/taxonomy_term/mod.rs
> +        for child_id in payload.entity_ids.clone() {
```suggestion
        for child_id in payload.entity_ids {
```

Use `*child_id` instead of `child_id` then

2022-05-05 07:59 UTC, kulla commented on server/src/uuid/model/taxonomy_term/mod.rs
> +                });
```suggestion
                continue;
```

2022-05-05 07:59 UTC, kulla commented on server/tests/taxonomy_term.rs
> +    async fn fails_if_link_already_exists() {
Check that link is not stored twice.

2022-05-05 08:24 UTC, hugotiburtino commented on server/src/uuid/model/entity/mod.rs
> -        Entity::add_revision(
We have meanwhile a way better [integration test](https://github.com/serlo/serlo.org-database-layer/blob/main/server/tests/entity.rs#L24) for that.

2022-05-05 09:12 UTC, kulla commented on server/src/uuid/model/entity/mod.rs
> -        Entity::add_revision(
then you need to delete the whole test function...

2022-05-06 12:18 UTC, kulla commented on server/tests/taxonomy_term.rs
> +    async fn fails_if_link_already_exists() {
No, it shouldn't throw an error...

2022-05-06 12:20 UTC, hugotiburtino commented on server/tests/taxonomy_term.rs
> +    async fn fails_if_link_already_exists() {
check

2022-05-06 20:21 UTC, kulla approved these changes

2022-05-06 21:23 UTC, merged