Add TaxonomyDeleteEntityLinkMutation
serlo/serlo.org-database-layer pull request #222
Opened 2022-04-30 23:02 UTC by hugotiburtino

Resolves #211

2022-05-05 08:10 UTC, kulla requested changes

2022-05-05 08:10 UTC, kulla commented on server/src/uuid/model/taxonomy_term/mod.rs
> +        for child_id in payload.entity_ids.clone() {
```suggestion
        for child_id in payload.entity_ids {
```

2022-05-05 08:10 UTC, kulla commented on server/src/uuid/model/taxonomy_term/mod.rs
> +
Add check that `entity` has also another link to another taxonomy term (we do not want to have entties without a link to a taxonomy term)

2022-05-06 09:19 UTC, hugotiburtino commented
@kulla please re-review it

2022-05-06 10:02 UTC, merged