wip: POST /thread/set-archive
serlo/serlo.org-database-layer pull request #61
Opened 2021-01-29 12:09 UTC by elbotho

**Status:**
Everything's prepared for the real magic 😉 

**Todo**
- Fix comment insert query
- insert event and event parameter
- insert subscriptions?

----
**Actual queries legacy sends when adding comment.** 

Maybe helpful?
``` sql
START TRANSACTION

INSERT INTO uuid (trashed, discriminator) 
    VALUES (0, 'comment')

INSERT INTO comment ( id , date , archived , title , content , uuid_id , parent_id , author_id , instance_id )
    VALUES ( 35610 , '2021-01-29 02:26:19' , 0 , NULL , 'XANTWORTX' , NULL , 35609 , 1 , 1 )

INSERT INTO event_log ( date , actor_id , event_id , uuid_id , instance_id )
    VALUES ( '2021-01-29 02:26:20' , 1 , 9 , 35610 , 1 )
    
INSERT INTO event_parameter ( log_id , name_id )
    VALUES ( 86593 , 5 )
    
INSERT INTO event_parameter_uuid ( event_parameter_id , uuid_id )
    VALUES ( 70043 , 35609 )

COMMIT
```

2021-01-29 12:11 UTC, inyono commented
> Everything's prepared for the real magic 😉

Is that a "You can take over the PR now" 😁

2021-01-29 12:31 UTC, inyono commented
Depends on #62, #63

2021-01-30 23:51 UTC, inyono commented
FYI: one of the reasons the CI fails is because `sqlx-data.json` is not up-to-date anymore (because you added / changed queries). Can you tell me if/how that is impacting your local dev process? Or does SQLX just ignore that with `cargo run`?

2021-01-31 00:31 UTC, elbotho commented
>  you tell me if/how that is impacting your local dev process?

Jup, no effect on `cargo test` and `cargo run` as far as I can tell.


Okay! #62 and #63 are added. 

**Todos:**
- figure out why comment `INSERT` query fails with `Err(DatabaseError { inner: RowNotFound })` even though the exact steps work manually with SQL. `cargo test thread` to run debug test.
- if that works, add test for successful cases.
- Check: Is the subscription to the thread or the comment?
- ?

2021-01-31 10:00 UTC, elbotho commented
BTW: how can I update `sqlx-data.json` or make the checks pass again?

2021-02-02 12:29 UTC, inyono requested changes

2021-02-02 12:29 UTC, inyono commented on src/subscriptions/model.rs
> +                (SELECT id FROM subscription WHERE uuid_id = ? AND user_id = ?)
This doesn't have the correct behavior yet. If the subscription already exists, we should still update `notify_mailman`.

2021-02-02 12:29 UTC, inyono commented on src/threads/model.rs
> +    #[error("Comment could not be saved because of a database error: {inner:?}.")]
Typo

2021-02-02 12:29 UTC, inyono commented on src/threads/model.rs
> +            send_email: true,
@inyono: Review that. Although I wouldn't be surprised if that is the behavior of legacy ^^'

2021-02-02 12:29 UTC, inyono commented on src/threads/model.rs
> +        .unwrap();
we can use `Uuid` here.

2021-02-02 12:29 UTC, inyono commented on src/threads/routes.rs
> +                    HttpResponse::InternalServerError().json(None::<String>)
These shouldn't have a response body.

2021-02-02 12:32 UTC, inyono commented on src/threads/model.rs
> +    #[error("Comment could not be saved because of a database error: {inner:?}.")]
Also the format doesn't follow our existing errors.

2021-02-02 12:36 UTC, inyono commented on src/threads/model.rs
> +            send_email: true,
Okay. This should actually be a param in the payload (if you want to subscribe and if you want to get emails).

2021-02-02 12:49 UTC, inyono commented on src/threads/model.rs
> +            send_email: true,
https://github.com/serlo/api.serlo.org/issues/234

2021-02-02 12:51 UTC, inyono commented
> BTW: how can I update `sqlx-data.json` or make the checks pass again?

- `cargo install sqlx-cli` once and then
- `cargo sqlx prepare -- --lib` to update sqlx-data.json

I'll update the README soon but wanted to have a feeling how this thing works before that ;)

2021-02-04 16:49 UTC, inyono approved these changes

2021-02-04 16:58 UTC, merged